export const FETCH_COUNTRIES = 'COUNTRY/FETCH_COUNTRIES'
export const FETCH_BY_COUNTRY = 'COUNTRY/FETCH_BY_COUNTRY'

export const SELECT_COUNTRY = 'COUNTRY/SELECT_COUNTRY'
export const SELECT_CASE = 'COUNTRY/SELECT_CASE'
export const SELECT_DATE_FROM = 'COUNTRY/SELECT_DATE_FROM'
export const SELECT_DATE_FROM_RANGE = 'COUNTRY/SELECT_DATE_FROM_RANGE'

export const FILTERED_DATA = 'COUNTRY/FILTERED_DATA'
