export const SHOW_LOADING = 'APP/SHOW_LOADING'
export const HIDE_LOADING = 'APP/HIDE_LOADING'

export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'

export const TOGGLE_NAVIGATION = 'APP/TOGGLE_NAVIGATION'
