export const FETCH_DATA = 'GLOBAL/FETCH_DATA'

export const SET_DATE_FROM_RANGE = 'GLOBAL/SET_DATE_FROM_RANGE'
export const SET_DATE_TO_RANGE = 'GLOBAL/SET_DATE_TO_RANGE'

export const SELECT_CASE = 'GLOBAL/SELECT_CASE'
export const SELECT_DATE_FROM = 'GLOBAL/SELECT_DATE_FROM'
export const SELECT_DATE_TO = 'GLOBAL/SELECT_DATE_TO'

export const FILTERED_DATA = 'GLOBAL/FILTERED_DATA'
